src/actions/bank-accounts.js, src/actions/categories.js, src/components/bank-accounts/select-field.tsx, src/components/categories/select-field.tsx, src/components/transactions/form.jsx, src/model-types.ts, src/sagas/bank-accounts.js, src/sagas/categories.js
https://trello.com/c/9QiVgZCV/471-make-component-to-select-bank-account
https://trello.com/c/8a2ZfQ6o/472-make-component-to-select-category
=> add bank-accounts and categories selects

src/components/transactions/new/expense.jsx, src/components/transactions/new/income.jsx, src/components/transactions/new/transfer.jsx, src/model-types.ts, src/utils/money/money.ts
https://trello.com/c/fnJ9J8hq/480-%D0%B2-%D1%84%D0%BE%D1%80%D0%BC%D0%B5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%BF%D0%BE%D0%BB%D0%B5-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0-amount
=> fix amount issue with new transaction

src/actions/transactions.js, src/api/transactions.js, src/components/transactions/destroy.tsx, src/components/transactions/edit/expense.jsx, src/components/transactions/edit/income.jsx, src/components/transactions/edit/transfer.jsx, src/components/transactions/form/destroy.tsx, src/components/transactions/form/form.jsx, src/components/transactions/form/transfer-form.jsx, src/sagas/transactions.js
https://trello.com/c/zHWjj4hJ/475-transactions-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%83%D0%B4%D0%B0%D0%BB%D1%8F%D1%82%D1%8C-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8
=> feat: transactions destroy

package.json, src/actions/bank-accounts.js, src/components/bank-accounts/bank-account-name.tsx, src/components/bank-accounts/bank-accounts.jsx, src/components/bank-accounts/select-field.tsx, src/components/layouts/sidebar/bank-accounts.jsx, src/components/transactions/list/table-row.tsx, src/model-types.ts, src/reducers/bank-account.js, src/reducers/bank-accounts.js, src/sagas/bank-accounts.js, src/utils/bank-account/bank-account.ts, src/utils/bank-account/index.ts, yarn.lock
https://trello.com/c/9QiVgZCV/471-make-component-to-select-bank-account
=> update bank account components

src/components/organizations/select.jsx
https://trello.com/c/YX6Gv4ga/478-organizations-change-layout-for-select-organization
=> update select organization component

src/components/organizations/form.jsx, src/components/organizations/new.jsx
https://trello.com/c/pll3urLV/386-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%83%D1%8E-%D1%84%D0%BE%D1%80%D0%BC%D1%83-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8
=> update organization components

src/components/members/members.jsx
https://trello.com/c/i75lhRfN/410-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-crud-%D0%BF%D0%BE-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F%D0%BC%D0%B8-%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8
=> update members component

src/actions/balances.js, src/components/layouts/main-menu/balance-item.tsx, src/components/layouts/main-menu/balances.tsx, src/components/layouts/sidebar/bank-accounts.jsx, src/reducers/balances.js, src/sagas/balances.js
https://trello.com/c/jIcigFBL/413-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%D0%B0-%D0%BF%D0%BE-%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%BC%D1%83-%D1%81%D1%87%D1%91%D1%82%D1%83-sidebar
=> update sidebar and balances menu

src/components/transactions/destroy.tsx
https://trello.com/c/zHWjj4hJ/475-transactions-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%83%D0%B4%D0%B0%D0%BB%D1%8F%D1%82%D1%8C-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8
=> add confirm to transactions destroy

src/components/organizations/list/list-item.jsx, src/components/organizations/list/organizations.jsx, src/components/organizations/select.jsx, src/selectors/organizations.js
https://trello.com/c/flD810ri/487-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%B0-%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D1%81%D0%BF%D0%B8%D0%BD%D0%B5%D1%80-%D0%BF%D1%80%D0%B8-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B9
=> update select organization components

src/components/transactions/css/default.css, src/components/transactions/list.tsx, src/components/transactions/new.tsx, src/components/transactions/scene.tsx
https://trello.com/c/x1IETqXe/479-transactions-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D1%84%D0%BE%D1%80%D0%BC%D1%83-%D1%81%D0%BE%D0%B7%D0%B0%D0%B4%D0%BD%D0%B8%D1%8F-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F
=> update transactions flow

src/components/invoices/complete.tsx, src/components/invoices/edit.tsx, src/components/invoices/form/form.tsx, src/components/invoices/form/item-fields.tsx, src/components/invoices/form/main-fields.tsx, src/components/invoices/new.tsx
https://trello.com/c/uUwxiNdd/477-invoices-show-items
=> update invoice components, fix form

src/components/user/profile-form.jsx, src/components/user/profile-wrapper.jsx
https://trello.com/c/qVXl48fU/483-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8C-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8E-%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%B0
=> fix profile components

src/components/invoices/edit.tsx, src/components/invoices/form/form.tsx, src/components/invoices/form/item-fields.tsx, src/components/invoices/form/items-fields.tsx, src/components/invoices/form/remove-item.tsx, src/model-types.ts
https://trello.com/c/Rs36Jktk/465-invoices-edit-edit-items
=>  feat(InvoiceItems): implement remove flow

src/components/categories/select-field.tsx, src/services/categories/selectors.js
https://trello.com/c/5zoNNs6e/526-%D0%BF%D1%80%D0%B8-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B8-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%BF%D1%83%D1%81%D1%82%D0%BE%D0%B9-%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%BF%D1%80%D0%B8-%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%B5-%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D0%B8
=> fix categories

jsconfig.json, src/components/bank-accounts/edit.jsx, src/components/bank-accounts/form.jsx, src/components/bank-accounts/list.tsx, src/components/bank-accounts/list/table-row.tsx, src/components/bank-accounts/list/table.tsx, src/components/bank-accounts/new.jsx, src/components/bank-accounts/select-field.tsx, src/components/invoices/debtors-sidebar/debtors-sidebar.tsx, src/components/invoices/edit.tsx, src/components/invoices/list/all.tsx, src/components/invoices/list/unpaid.tsx, src/components/invoices/show.tsx, src/components/layouts/sidebar/bank-accounts-table.tsx, src/components/layouts/sidebar/bank-accounts.tsx, src/components/transactions/edit.tsx, src/components/transactions/list.tsx, src/components/transactions/list/table-row.tsx, src/components/utils/loading-view/loading-view.tsx, src/services/bank-accounts/actions.js, src/services/bank-accounts/api.js, src/services/bank-accounts/saga.js, src/services/bank-accounts/selectors.js, src/services/bank-accounts/types.ts, src/services/bank-accounts/visible-entities-reducer.js, src/services/reducers.js
https://trello.com/c/ndUS8P1y/525-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%87%D0%B5%D1%82%D0%BE%D0%B2
=> Update bank accounts

src/components/bank-accounts/select-field.tsx, src/components/categories/select-field.tsx, src/components/currencies/select-field.tsx, src/components/customers/select-field.tsx
https://trello.com/c/RoshYqvZ/552-%D0%B2-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%B0%D1%85-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%B0-%D0%B1%D1%8B%D1%82%D1%8C-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B0-%D0%BE%D1%82%D1%87%D0%B8%D1%81%D1%82%D0%B8%D1%82%D1%8C
=> feat: allow to clear select fields

src/components/invoices/complete.tsx, src/services/transactions/types.ts
https://trello.com/c/73YVT99U/547-%D0%BF%D1%80%D0%B8-complete-%D0%B8%D0%BD%D0%B2%D0%BE%D0%B9%D1%81%D0%B0-%D0%BE%D0%BD-%D0%BD%D0%B5-%D0%BF%D0%BE%D0%BC%D0%B5%D1%87%D0%B0%D0%B5%D1%82%D1%81%D1%8F-%D0%BA%D0%B0%D0%BA-%D0%BE%D0%BF%D0%BB%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9
=> fix(Invoice): mark invoice as complete

src/components/transactions/filter/form.tsx, src/components/transactions/filter/period-select.tsx
https://trello.com/c/NyrZCbs9/585-transactions-%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%BE-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE-%D0%B4%D0%B0%D1%82%D0%B5-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8E-%D0%BF%D0%BE-%D0%BF%D0%B5%D1%80%D0%B8%D0%BE%D0%B4%D1%83
=> feat(Transactions): filter by period

src/components/layouts/main-menu/balances.tsx, src/components/layouts/main-menu/invoices.tsx, src/components/layouts/main-menu/main-menu.tsx, src/components/layouts/main-menu/organization-item.tsx, src/components/layouts/main-menu/profile-item.tsx
https://trello.com/c/Ey1Ekkpz/593-%D0%B2-%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8-%D1%81%D0%B2%D0%BE%D1%80%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D1%82%D1%8C-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5-%D0%BC%D0%B5%D0%BD%D1%8E
=> feat(Main menu): collapse on small screens

src/components/transactions/new/normal.tsx, src/store.ts
https://trello.com/c/c8mMkAtg/588-%D0%BF%D1%80%D0%B8-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B8-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%B5%D1%81%D0%BB%D0%B8-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80-%D1%82%D0%BE-%D1%81%D0%BE%D0%BE%D1%82%D0%B2%D0%B5%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D0%B5-%D0%BF%D0%BE%D0%BB%D1%8F-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B-%D0%B1%D1%8B%D1%82%D1%8C-%D0%B7%D0%B0%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D1%8B-%D0%B8%D0%B7-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0
=> Prefill transaction from filter

src/components/invoices/debtors-sidebar/debtors-sidebar.tsx, src/components/invoices/destroy.tsx, src/components/invoices/show.tsx, src/services/debtors/reducers/debtors.js
https://trello.com/c/MiqEbB5o/600-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D1%8F%D1%82%D1%8C-%D0%B4%D0%B5%D0%B1%D0%B8%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B8%D0%B9-%D1%81%D0%B0%D0%B9%D0%B4%D0%B1%D0%B0%D1%80-%D0%BF%D1%80%D0%B8-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8-%D0%B8%D0%BD%D0%B2%D0%BE%D0%B9%D1%81%D0%BE%D0%B2
=> Refresh debtor sidebar

src/components/bank-accounts/filter-link.tsx, src/components/bank-accounts/select-field.tsx, src/components/categories/filter-link.tsx, src/components/categories/select-field.tsx, src/components/customers/filter-link.tsx, src/components/customers/select-field.tsx, src/components/organizations/current-organization/consumer.tsx, src/components/transactions/filter/filter.tsx, src/components/transactions/filter/form.tsx, src/components/transactions/new/normal.tsx, src/components/utils/form-inputs/date-picker.tsx, src/components/utils/form-inputs/no-label-form-group.tsx, src/services/transactions/selectors.ts, src/services/transactions/types.ts, src/utils/url-helpers/url-helpers.ts
https://trello.com/c/vGtf01QT/594-transactions-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D0%BC-%D1%81%D1%87%D0%B5%D1%82%D0%B0%D0%BC
https://trello.com/c/6gggaElp/595-transactions-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D0%BC-%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F%D0%BC
https://trello.com/c/vw8JGvIQ/596-transactions-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8 …
=> Filter by several bank accounts/customers/categories

src/components/categories/list.tsx, src/components/categories/list/table.tsx
https://trello.com/c/76aAvxXf/606-%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D0%B8-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%BC%D0%B5%D0%BD%D1%82%D0%B0-%D1%80%D0%B0%D0%B7%D0%B1%D0%B8%D1%82%D1%8C-%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%BD%D0%B0-%D1%82%D0%B8%D0%BF%D1%8B-%D0%B2%D0%BD%D1%83%D1%82%D1%80%D0%B8-%D1%82%D0%B8%D0%BF%D0%B0-%D1%81%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE-%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%82%D1%83
=> update categories ordering

src/components/transactions/filter/form.tsx, src/components/transactions/filter/period-select.tsx, src/services/transactions/selectors.ts, src/services/transactions/types.ts
https://trello.com/c/wAclePWM/586-transactions-%D0%B2-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8E-%D0%BF%D0%BE-%D0%BF%D0%B5%D1%80%D0%B8%D0%BE%D0%B4%D1%83-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%BD%D1%8B%D0%B9-%D0%BF%D0%B5%D1%80%D0%B8%D0%BE%D0%B4
=> feat: add custom period to transactions filter

src/components/statistic/categories/page.tsx, src/components/statistic/customers/income-chart.tsx, src/components/statistic/customers/income-provider.tsx, src/components/statistic/customers/page.tsx, src/components/statistic/menu.tsx, src/components/statistic/period-tabs.tsx, src/components/statistic/scene.tsx, src/routes.ts, src/services/global-state.ts, src/services/reducers.ts, src/services/statistic/actions.ts, src/services/statistic/api.ts, src/services/statistic/reducers/income-customers-statistic.ts, src/services/statistic/saga.ts, src/services/statistic/selectors.ts, src/services/statistic/types.ts
https://trello.com/c/tFq5RUPD/610-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-income-by-customers
=> Add income by customers chart

src/components/statistic/customers/chart.tsx, src/components/statistic/customers/expense-provider.tsx, src/components/statistic/customers/page.tsx, src/services/global-state.ts, src/services/reducers.ts, src/services/statistic/actions.ts, src/services/statistic/api.ts, src/services/statistic/reducers/expense-customers-statistic.ts, src/services/statistic/saga.ts, src/services/statistic/selectors.ts, src/services/statistic/types.ts
https://trello.com/c/PZsb5BDl/611-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-expense-by-customers
=> Add expense by customers chart

src/components/statistic/customers/page.tsx, src/components/statistic/customers/totals-by-provider.tsx, src/services/global-state.ts, src/services/reducers.ts, src/services/statistic/actions.ts, src/services/statistic/api.ts, src/services/statistic/reducers/totals-by-customers-statistic.ts, src/services/statistic/saga.ts, src/services/statistic/selectors.ts, src/services/statistic/types.ts
https://trello.com/c/4eMth7XL/612-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-total-by-customers
=> feat: add totals by customers chart

src/components/statistic/customers/balances-by-provider.tsx, src/components/statistic/customers/balances-chart.tsx, src/components/statistic/customers/page.tsx, src/components/statistic/customers/totals-by-provider.tsx, src/components/statistic/menu.tsx, src/services/global-state.ts, src/services/reducers.ts, src/services/statistic/actions.ts, src/services/statistic/api.ts, src/services/statistic/reducers/balances-by-customers-statistic.ts, src/services/statistic/reducers/totals-by-customers-statistic.ts, src/services/statistic/saga.ts, src/services/statistic/selectors.ts, src/services/statistic/types.ts
https://trello.com/c/wzRNPynQ/613-statistic-%D0%B7%D0%B0%D0%BF%D0%BE%D0%BC%D0%B8%D0%BD%D0%B0%D1%82%D1%8C-%D0%B2%D1%8B%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9-%D0%BF%D0%B5%D1%80%D0%B8%D0%BE%D0%B4-%D0%BF%D1%80%D0%B8-%D1%81%D0%BC%D0%B5%D0%BD%D0%B5-%D1%82%D0%B8%D0%BF%D0%B0-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B8
=> feat: add balances by customers chart, keep statistic period

src/components/statistic/categories/chart.tsx, src/components/statistic/customers/chart.tsx, src/components/statistic/customers/page.tsx
https://trello.com/c/0NYwQiqP/616-statistics-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D1%80%D1%83%D0%B3%D0%BE%D0%B2%D1%8B%D1%85-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC
=> update round charts

src/components/statistic/categories/chart.tsx, src/components/statistic/customers/chart.tsx
https://trello.com/c/qpO3twCz/617-statistics-%D0%B4%D0%BB%D1%8F-%D0%BA%D1%80%D1%83%D0%B3%D0%BE%D0%B2%D1%8B%D1%85-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC-%D0%BB%D0%B5%D0%B3%D0%B5%D0%BD%D0%B4%D1%83-%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D0%B2%D0%BB%D0%B5%D0%B2%D0%BE
=> update charts legend view

src/components/invoices/show/items.tsx, src/services/invoices/types.ts
https://trello.com/c/UtZajLmg/623-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B0-%D0%B8%D0%BD%D0%B2%D0%BE%D0%B9%D1%81%D0%B0-%D0%BD%D0%B5-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D0%B5%D1%82%D1%81%D1%8F-%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%B5%D1%80
=> update invoice items

src/components/app/app.tsx, src/components/statistic/customers/by-months-chart.tsx, src/components/statistic/customers/expense-by-months-provider.tsx, src/components/statistic/customers/income-by-months-provider.tsx, src/components/statistic/customers/page.tsx, src/components/statistic/scene.tsx, src/services/global-state.ts, src/services/reducers.ts, src/services/statistic/actions.ts, src/services/statistic/api.ts, src/services/statistic/reducers/expense-customers-by-months-statistic.ts, src/services/statistic/reducers/income-customers-by-months-statistic.ts, src/services/statistic/saga.ts, src/services/statistic/selectors.ts, src/services/statistic/types.ts, yarn.lock
https://trello.com/c/Q1CTDvSI/618-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B0%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82-%D0%B4%D0%BB%D1%8F-%D0%B2%D1%81%D0%B5%D0%B3%D0%BE-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B0-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B8-%D0%B0-%D0%BD%D0%B5-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B8
=> update charts lazy import
